---
name: DateTime-Format-MySQL
version: 0.04
author:
  - Dave Rolsky <autarch@urth.org>
abstract: Parse and format MySQL dates and times
license: perl
requires:
  DateTime: 0
  DateTime::Format::Builder: 0.6
provides:
  DateTime::Format::MySQL:
    file: lib/DateTime/Format/MySQL.pm
    version: 0.04
generated_by: Module::Build version 0.2609
